CREATE TABLE IF NOT EXISTS SNET_AUDIT_STATISTICS (
	SEQ           			int NOT NULL,
	STATISTICS_ID 			varchar(32) COLLATE utf8_general_ci NOT NULL,
	BRANCH_ID	  			varchar(30) COLLATE utf8_general_ci NOT NULL,
	TEAM_ID		  			varchar(8) COLLATE utf8_general_ci NOT NULL,
	CREATE_DAY	  			varchar(12) COLLATE utf8_general_ci NOT NULL,
	AUDIT_STD_CD  			varchar(10) COLLATE utf8_general_ci NOT NULL,
	AD_RESULT_REQ 			int(11),
	AD_RESULT_OK  			int(11),
	AD_RESULT_NOK 			int(11),
	AD_RESULT_REQ_D			int(11),
	AD_RESULT_OK_D 			int(11),
	AD_RESULT_NOK_D			int(11),
	AD_EXCEPT_REQ 			int(11),
	AD_EXCEPT_OK  			int(11),
	AD_EXCEPT_NOK 			int(11),
	AD_EXCEPT_REQ_D			int(11),
	AD_EXCEPT_OK_D 			int(11),
	AD_EXCEPT_NOK_D			int(11),
	EQUIP_CNT	  			int(11),
	EQUIP_INSTALL_NOK_CNT   int(11),
	EQUIP_PLUS_CNT			int(11),
	EQUIP_MINUS_CNT			int(11),
	EQUIP_CNT_D	  			int(11),
	EQUIP_INSTALL_NOK_CNT_D int(11),
	EQUIP_PLUS_CNT_D		int(11),
	EQUIP_MINUS_CNT_D		int(11),
	SW_TYPE					varchar(30) COLLATE utf8_general_ci,
	ASSET_NOT_AUDIT_CNT		int(11),
	ASSET_NOT_COK_CNT		int(11),
	ASSET_CNT				int(11),
	ASSET_PLUS_CNT			int(11),
	ASSET_MINUS_CNT		    int(11),
	ASSET_NOT_AUDIT_CNT_D	int(11),
	ASSET_NOT_COK_CNT_D		int(11),
	ASSET_CNT_D				int(11),
	ASSET_PLUS_CNT_D		int(11),
	ASSET_MINUS_CNT_D	    int(11),
	ITEM_CNT				int(11),
	ALL_ITEM_CNT			int(11),
	SCHK_SEC_VAL			decimal(6,3),
	SCHK_SEC_LEV			varchar(30),
	PCHK_SEC_VAL			decimal(6,3),
	PCHK_SEC_LEV			varchar(30),
	AUDIT_RATE				decimal(6,3),
	ALL_AUDIT_RATE			decimal(6,3),
	ALL_AUDIT_RATE_AVG		decimal(6,3),
	BRANCH_AUDIT_RATE		decimal(6,3),
	BRANCH_AUDIT_RATE_AVG 	decimal(6,3),
	TEAM_AUDIT_RATE		 	decimal(6,3),
	TEAM_AUDIT_RATE_AVG	 	decimal(6,3),
	ITEM_CNT_D				int(11),
	ALL_ITEM_CNT_D			int(11),
	SCHK_SEC_VAL_D			decimal(6,3),
	SCHK_SEC_LEV_D			varchar(30),
	PCHK_SEC_VAL_D			decimal(6,3),
	PCHK_SEC_LEV_D			varchar(30),
	AUDIT_RATE_D			decimal(6,3),
	ALL_AUDIT_RATE_D		decimal(6,3),
	ALL_AUDIT_RATE_AVG_D	decimal(6,3),
	BRANCH_AUDIT_RATE_D		decimal(6,3),
	BRANCH_AUDIT_RATE_AVG_D	decimal(6,3),
	TEAM_AUDIT_RATE_D	 	decimal(6,3),
	TEAM_AUDIT_RATE_AVG_D 	decimal(6,3),
	DIVISION	       		varchar(30) COLLATE utf8_general_ci NOT NULL,
	primary key (SEQ, STATISTICS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS SNET_AUDIT_STATISTICS_DETAIL (
	DETAIL_SEQ				 	int(11) NOT NULL primary key AUTO_INCREMENT,
	SEQ						 	int(11) NOT NULL,
	STATISTICS_ID			 	varchar(32) COLLATE utf8_general_ci NOT NULL,
	BRANCH_ID				 	varchar(30) COLLATE utf8_general_ci NOT NULL,
	TEAM_ID					 	varchar(8) COLLATE utf8_general_ci NOT NULL,
	CREATE_DAY				 	varchar(12) COLLATE utf8_general_ci NOT NULL,
	ASSET_CD			     	varchar(30) COLLATE utf8_general_ci NOT NULL,
	SW_NM					 	varchar(30) COLLATE utf8_general_ci,
	HOST_NM					 	varchar(50) COLLATE utf8_general_ci ,
	AUDIT_RATE				 	decimal(6,3),
	WEAK_CNT				 	int(11),
	SW_NM_D					 	varchar(30) COLLATE utf8_general_ci,
	HOST_NM_D				 	varchar(50) COLLATE utf8_general_ci ,
	AUDIT_RATE_D			 	decimal(6,3),
	WEAK_CNT_D				 	int(11),
	ITEM_GRP_NM				 	varchar(30) COLLATE utf8_general_ci,
	ITEM_GRP_SEC_VAL		 	decimal(6,3),
	ITEM_GRP_CNT			 	int(11),
	ITEM_GRP_GOOD_CNT		 	int(11),
	ITEM_GRP_WEAK_CNT		 	int(11),
	ITEM_GRP_NA_CNT			 	int(11),
	ITEM_GRP_RISK_CNT		 	int(11),
	ITEM_GRP_ALL_CNT		 	int(11),
	ITEM_GRP_NM_D			 	varchar(30) COLLATE utf8_general_ci,
	ITEM_GRP_SEC_VAL_D		 	decimal(6,3),
	ITEM_GRP_CNT_D			 	int(11),
	ITEM_GRP_GOOD_CNT_D		 	int(11),
	ITEM_GRP_WEAK_CNT_D		 	int(11),
	ITEM_GRP_NA_CNT_D		 	int(11),
	ITEM_GRP_RISK_CNT_D		 	int(11),
	ITEM_GRP_ALL_CNT_D		 	int(11),
	WEAK_HIGH_RATE              decimal(6,3),
	WEAK_MID_RATE               decimal(6,3),
	WEAK_LOW_RATE               decimal(6,3),
	WEAK_HIGH_RATE_D            decimal(6,3),
	WEAK_MID_RATE_D             decimal(6,3),
	WEAK_LOW_RATE_D             decimal(6,3),
	WEAK_HIGH_CNT			 	int(11),
	WEAK_MID_CNT			 	int(11),
	WEAK_LOW_CNT			 	int(11),
	WEAK_HIGH_CNT_D			 	int(11),
	WEAK_MID_CNT_D			 	int(11),
	WEAK_LOW_CNT_D			 	int(11),
	AD_RESULT_HIGH_AWEEK_CNT 	int(11),
	AD_RESULT_HIGH_BWEEK_CNT 	int(11),
	AD_RESULT_HIGH_CWEEK_CNT 	int(11),
	AD_RESULT_HIGH_DWEEK_CNT 	int(11),
	AD_RESULT_MID_AWEEK_CNT  	int(11),
	AD_RESULT_MID_BWEEK_CNT  	int(11),
	AD_RESULT_MID_CWEEK_CNT  	int(11),
	AD_RESULT_MID_DWEEK_CNT  	int(11),
	AD_RESULT_LOW_AWEEK_CNT  	int(11),
	AD_RESULT_LOW_BWEEK_CNT  	int(11),
	AD_RESULT_LOW_CWEEK_CNT  	int(11),
	AD_RESULT_LOW_DWEEK_CNT  	int(11),
	AD_RESULT_HIGH_AWEEK_CNT_D	int(11),
	AD_RESULT_HIGH_BWEEK_CNT_D	int(11),
	AD_RESULT_HIGH_CWEEK_CNT_D	int(11),
	AD_RESULT_HIGH_DWEEK_CNT_D	int(11),
	AD_RESULT_MID_AWEEK_CNT_D	int(11),
	AD_RESULT_MID_BWEEK_CNT_D	int(11),
	AD_RESULT_MID_CWEEK_CNT_D	int(11),
	AD_RESULT_MID_DWEEK_CNT_D	int(11),
	AD_RESULT_LOW_AWEEK_CNT_D	int(11),
	AD_RESULT_LOW_BWEEK_CNT_D	int(11),
	AD_RESULT_LOW_CWEEK_CNT_D	int(11),
	AD_RESULT_LOW_DWEEK_CNT_D	int(11),
	AD_EXCEPT_HIGH_AWEEK_CNT	int(11),
	AD_EXCEPT_HIGH_BWEEK_CNT	int(11),
	AD_EXCEPT_HIGH_CWEEK_CNT	int(11),
	AD_EXCEPT_HIGH_DWEEK_CNT	int(11),
	AD_EXCEPT_MID_AWEEK_CNT		int(11),
	AD_EXCEPT_MID_BWEEK_CNT		int(11),
	AD_EXCEPT_MID_CWEEK_CNT		int(11),
	AD_EXCEPT_MID_DWEEK_CNT		int(11),
	AD_EXCEPT_LOW_AWEEK_CNT		int(11),
	AD_EXCEPT_LOW_BWEEK_CNT		int(11),
	AD_EXCEPT_LOW_CWEEK_CNT		int(11),
	AD_EXCEPT_LOW_DWEEK_CNT		int(11),
	AD_EXCEPT_HIGH_AWEEK_CNT_D	int(11),
	AD_EXCEPT_HIGH_BWEEK_CNT_D	int(11),
	AD_EXCEPT_HIGH_CWEEK_CNT_D	int(11),
	AD_EXCEPT_HIGH_DWEEK_CNT_D	int(11),
	AD_EXCEPT_MID_AWEEK_CNT_D	int(11),
	AD_EXCEPT_MID_BWEEK_CNT_D	int(11),
	AD_EXCEPT_MID_CWEEK_CNT_D	int(11),
	AD_EXCEPT_MID_DWEEK_CNT_D	int(11),
	AD_EXCEPT_LOW_AWEEK_CNT_D	int(11),
	AD_EXCEPT_LOW_BWEEK_CNT_D	int(11),
	AD_EXCEPT_LOW_CWEEK_CNT_D	int(11),
	AD_EXCEPT_LOW_DWEEK_CNT_D	int(11),
	DIVISION					varchar(30) COLLATE utf8_general_ci NOT NULL,
	constraint fk_snet_audit_statistics_detail foreign key (SEQ, STATISTICS_ID) references SNET_AUDIT_STATISTICS (SEQ, STATISTICS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table SNET_AUDIT_STATISTICS_DETAIL AUTO_INCREMENT=1;
alter table SNET_AUDIT_STATISTICS AUTO_INCREMENT=1;

create index SNET_AUDIT_STATISTICS01 on SNET_AUDIT_STATISTICS (CREATE_DAY);
create index SNET_AUDIT_STATISTICS_DETAIL01 on SNET_AUDIT_STATISTICS_DETAIL (CREATE_DAY);